### ISSUE TITLE
Error auf gh-pages

### ISSUE THREAD

**Issue by t-duan** [JULIELab/julielab.github.io#1]
auf gh-pages Branch gibt's problem, s. https://www.smashingmagazine.com/2014/08/build-blog-jekyll-github-pages/
Common problem #3: Using a project website for your Jekyll website  @benjamir troduces some complexity because your website will be published to a subdirectory. The URL will look like http://yourname.github.io/repository-name, which will cause problems in Jekyll templates, such as breaking references to images and not letting you preview the website locally.y.

**Comment by benjamir** [comment]
https://github.com/barryclark/jekyll-now/blob/master/_config.yml
...
~~~
# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""
~~~
...
=> baseurl: "/web"

**Comment by benjamir** [comment]
Tried to set "baseurl" to the current reponame (web) and changed default branch and web site build to branch "gh-pages". But that didn't work out as expected. Maybe I did something wrong.
Anyway, we should just migrate the content from the old page to the repo (probably easiest via pandoc) and then go online as soon as possible. Little quirks at the new site are not relevant.
