### ISSUE TITLE
rework old URL schema

### ISSUE THREAD

**Issue by chlor** [JULIELab/julielab.github.io#3]
One URL schema for staff:
https://julielab.github.io/web/staff/ChristinaLohr
https://julielab.github.io/web/staff/Matthies/Franz+Matthies.html
should be one schema.

**Comment by t-duan** [comment]
Maybe we should discuss this issue in the group, before we change all URLs. It costs much time.

**Comment by benjamir** [comment]
Sorry, but that solution in its current incarnation is slightly flawed
**Good**: the redirect to the old name schema. Thanks for that! That's the **key to the full solution**.
**Issue**: the old URL schema was e.g. https://julielab.github.io/web/staff/Franz+Matthies.html
The directory named with the surname after "staff" is superfluous.
Should be repairable by moving the HTML pages to the parent dir, but watch out for side-effects with the per person sub-pages (publications, etc.)

**Comment by benjamir** [comment]
I would go with the old schema -- even if it is a bit verbose -- to keep the ranking in the search engines and links from outside will still work!

**Comment by chlor** [comment]
Ja, ich weiß, dass ich eigentlich GitHub verwenden sollte, aber das  
alte Schema finde ich nicht "schön". Ich wollte das mit auf die  
Visitenkarte drucken und da kam das nicht gut, und war zu lang. Vlt.  
doch nochmal in der Gruppe fragen?


Zitat von Benjamin <notifications@github.com>:

**Comment by chlor** [comment]
I would print the URL on my visiting card and the old schema is too  
long and contains enough charcters without information.


Zitat von Benjamin <notifications@github.com>:

**Comment by t-duan** [comment]
I saw some scientists use a permanent link like "http://purl.org/dm". You can register one at purl.org and redirect it to your current homepage.

**Comment by benjamir** [comment]
We can migrate to the short version later on -- with redirects
I don't know if the redirect_to gem and the necessary front matter is a feasible long-term solution. There is also redirect_from  (https://github.com/jekyll/jekyll-redirect-from) which might be easier to take care of because it only needs at the active page -- somebody has to keep that in mind while moving things around, but at least the redirects are not all over the directory tree.

**Comment by t-duan** [comment]
In any case, only one page should bei modified, in order to change the content. Maybe it'd be better to put all overview pages (e.g. Prof_+Dr_+Udo+Hahn.html) in /Staff and the "subpages" (publication.html) in the personal folder.

**Comment by benjamir** [comment]
Am 16.06.2018 um 22:22 schrieb Tinghui Duan:
> In any case, only one page should bei modified, in order to change the
> content. Maybe it'd be better to put all overview pages (e.g.
> Prof_+Dr_+Udo+Hahn.html) in /Staff and the "subpages" (publication.html)
> in the personal folder.

Same as before: we aim at first for the old schema.
That means the current
http://www.julielab.de/Staff/Prof_+Dr_+Udo+Hahn/Research-p-178.html
should work during the transition the GitHub pages based presence.

Benjamin
-- 
FSU Jena | JULIELab.de/Staff/Benjamin+Redling.html

**Comment by t-duan** [comment]
I understand. But in the future we redirect Research-p-178.html to research.html or vice versa? Should we keep the old tree structure?

**Comment by benjamir** [comment]
Am 17.06.2018 um 21:58 schrieb Tinghui Duan:
> I understand. But in the future we redirect Research-p-178.html to
> research.html or vice versa? Should we keep the old tree structure?

in the future we'll clean up and keep it nice, simple and tidy ;)

**Comment by benjamir** [comment]
Ok, final try:
**we don't want julielab.de/staff/\<surname\>/Givenname+Surname.html**
**The \<surename\> part is ill-fated; we didn't have that before and we won't have that in the future.**

We could have switched to the likely future schema julielab.de/staff/<GivennameSurname> if the index files wouldn't have been renamed to Givenname+Surname

**Comment by t-duan** [comment]
Maybe julielab.de/staff/Givenname+Surname.html and julielab.de/staff/Givenname+Surname/index.html?
Or without "+" between Givenname and Surname?

**Comment by svenbuechel** [comment]
Do we really need to install redirection from the old staff pages? At least, I won't be needing it.
Also, to add one more thing to the wish list: can we switch from plus "+" to hypen "-" or underscore "_"? E.g., `julielab.de/staff/Sven_Buechel`
I think that would look much better on a business card.

**Comment by benjamir** [comment]
Am 19. Juni 2018 20:28:28 MESZ, schrieb Sven Buechel <notifications@github.com>:
>Do we really need to install redirection from the old staff pages? At
>least, I won't be needing it.
>Also, to add one more thing to the wish list: can we switch from plus
>"+" to hypen "-" or underscore "_"? E.g.,
>`julielab.de/staff/Sven_Buechel`
>I think that would look much better on a business card.

Not necessarily, but links from outside will fail and one disadvantage of GH is that we cannot look into logs to find 404 -- but I haven't looked for it in their docs, might be possible there is a way to get that info (but doubt it)
--
FSU Jena | JULIELab.de/Staff/Benjamin+Redling.html
vox: +49 3641 9 44323 | fax: +49 3641 9 44321

**Comment by benjamir** [comment]
Am 19. Juni 2018 20:12:31 MESZ, schrieb Tinghui Duan <notifications@github.com>:
>Maybe julielab.de/staff/Givenname+Surname.html and
>julielab.de/staff/Givenname+Surname/index.html?
>Or without "+" between Givenname and Surname?

no

old one please, rest later.
wrote that multiple times...
--
FSU Jena | JULIELab.de/Staff/Benjamin+Redling.html
vox: +49 3641 9 44323 | fax: +49 3641 9 44321

**Comment by benjamir** [comment]
Ok, before every single URL quirk gets its own issue I change the name of this issue to something that reflects that **all** the URLs might need a rework (later).

**Comment by benjamir** [comment]
We had a short discussion and for all older URLs there seems to be a proper redirect.
* New entries are only ever created in the new, short style.
* Individually there's no restriction to remove one own's redirections in case someone gets confused with having multiple directories/files carrying their name.

I guess we are done with this issue, so far.
