### ISSUE TITLE
Edit-Button or Edit-Link?

### ISSUE THREAD

**Issue by chlor** [JULIELab/julielab.github.io#4]
Where is the buttun or the link to edit the website?

**Comment by eric24629** [comment]
Is that necessary to show it to all visitors? The URL will be "https://github.com/JULIELab/JULIELab.github.io".

**Comment by t-duan** [comment]
https://julielab.github.io/web/edit
Is this ok? @chlor

**Comment by benjamir** [comment]
(Ich brauche gar nichts davon.)
Aber vielleicht: https://github.com/jekyll/github-metadata/blob/master/docs/edit-on-github-link.md
?

**Comment by t-duan** [comment]
Guter Hinweis! Ein Edit-Button könnte ein bisschen Zeit sparen. Dann muss man nicht im Repo suchen. Andererseits wollten wir die Seite so übersichtlich und klar wie möglich. Ein zusätzliches Button finde ich nicht unbedingt nötig. Aber darüber kann man noch in der Gruppe diskutieren. Man kann die Funktion später hinzufügen.

**Comment by hellrich** [comment]
Es war auch mal julielab.de/edit als Link zum Repository im Gespräch, das fände ich gut zu merken

**Comment by t-duan** [comment]
Now it works with  www.julielab.de/edit. But if works only when in Github logged in.

**Comment by benjamir** [comment]
Am 19. Juni 2018 20:22:19 MESZ, schrieb Tinghui Duan <notifications@github.com>:
>Now it works with  www.julielab.de/edit. But if works only when in
>Github logged in.

Sure, it's a private repo. 
That cannot be changed as long as there's teaching material that shouldn't be public all the time.
--
FSU Jena | JULIELab.de/Staff/Benjamin+Redling.html
vox: +49 3641 9 44323 | fax: +49 3641 9 44321

**Comment by benjamir** [comment]
IMO this issue won't get fixed -- with a button.
Anybody from the team, please reopen if there's still a desire for that.
Better: provide a fix! :^)
