### ISSUE TITLE
Tables in Staff-Sites have to be adjusted

### ISSUE THREAD

**Issue by t-duan** [JULIELab/julielab.github.io#9]

**Comment by benjamir** [comment]
What do you mean by that?
I only noticed the "flicker" when a highlighted link gets bold and leads to a replacements of elements next to it. Do you have an idea for that? I didn't even look a possible solution up because my schedule doesn't currently allow for that.

**Comment by t-duan** [comment]
The problem mentioned in the titel was fixed. On the site of Prof. Hahn, if the screen is narrow, cells in the cv table were splitted. But it's fixed now.
The new problem is also fixed. No line will be splitted anymore.

**Comment by benjamir** [comment]
Have you noticed the offset rerendering of the columns right of "Associated Projects" on https://julielab.de/Staff.html when hovering "Graduate School" -- Johannes' project?

**Comment by t-duan** [comment]
You mean the column "E-mail" moves to the right? The same happens when hovering "Dr. Sascha Schäuble" in the column "name". Is that so bad?

**Comment by benjamir** [comment]
Am 27. Juni 2018 22:34:02 MESZ, schrieb Tinghui Duan <notifications@github.com>:
>You mean the column "E-mail" moves to the right? The same happens when
>hovering "Dr. Sascha Schäuble" in the column "name". Is that so bad?

Not too bad. I'm just curious what was the issue you fixed (I trust you); I seem to have overlooked something. I any major issue with the tables fixed feel free to close this one -- like any ticket you think that's done.
--
FSU Jena | JULIELab.de/Staff/Benjamin+Redling.html
vox: +49 3641 9 44323 | fax: +49 3641 9 44321

**Comment by t-duan** [comment]
Thanks für the trust :D The issue fixed was that sometimes a short single line was splitted into two lines. Now it doesn't do it anymore. The line "graduate school romantic model" is an except. Here I added a newline (<br\>) because this line is much longer than any others lines in the same column.
